version: '3.0.4'  
services:
  db:
    image: mysql:9.0.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: minecraft
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

  minecraft:
    build: .
    environment:
      MINECRAFT_EULA: "true"
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: minecraft
      DB_USER: root
      DB_PASSWORD: root
    ports:
      - "25565:25565"
    depends_on:
      - db

volumes:
  db_data:
